name: Production Enterprise CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-secure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Execute Unit Tests with Coverage
        run: |
          go test -v -race -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Linting check (golangci-lint)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59

      - name: Static Application Security Testing (SAST)
        uses: securego/gosec@master
        with:
          args: ./...

  build-and-ship:
    needs: validate-and-secure
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Enterprise Registry (AWS ECR / DockerHub)
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Immutable Tags
        id: meta
        run: |
          echo "SHA_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Push hardened image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            uvaishnav/go-web-app:latest
            uvaishnav/go-web-app:${{ env.SHA_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      update-newtag-in-helm-chart:
        runs-on: ubuntu-latest

        needs: push

    	steps:
    	- name: Checkout repository
      	  uses: actions/checkout@v4
      	  with:
            token: ${{ secrets.TOKEN }}
      	- name: Update tag in Helm chart
          run: |
            sed -i 's/tag: .*/tag: "${{env.SHA_TAG}}"/' helm/go-web-app-chart/values.yaml 
        - name: Commit and push changes
      	  run: |
            git config --global user.email "utkarshvaishnav295@gmail.com"
            git config --global user.name "Utk2022"
            git add helm/go-web-app-chart/values.yaml
            git commit -m "Update tag in Helm chart"
            git push
